Kanjis de avanzado 18/10/2024
eoi-japones/kanji-data pull request #133
Opened 2024-10-20 12:58 UTC by davconde

2024-10-20 13:00 UTC, davconde commented on data/争,contienda.yml
Actualizado al nombre de componente que ya teníamos (atado)

2024-10-21 11:55 UTC, frmadem requested changes

2024-10-21 11:55 UTC, frmadem commented on data/componentes/甫,chapa_de_perro.yml
> +  Cuando se estropea la chapa del collar del perro, la arreglas por primera vez
Los componentes están mal, son destornillador y punta de flecha

2024-10-21 11:55 UTC, frmadem commented on data/争,contienda.yml
> +  es que acaben con sus cabezas atadas (勹) entre ambos rastrillos (⺕).
El componente de rastrillo no es correcto, lo tengo que resolver yo (esto es correcto)

2024-10-21 11:55 UTC, frmadem commented on data/用,utilizar.yml
> +historia: Pictograma de un destornillador y un martillo.
Esta historia no la entienod bien, quizá tengamos que buscar otra (se te ocurre alguna)

2024-10-30 13:12 UTC, frmadem approved these changes
LGTM!

2024-10-30 16:33 UTC, merged