feat: Añadidos kanjis del mazo avanzado 2
eoi-japones/kanji-data pull request #15
Opened 2024-02-12 20:56 UTC by DjHexaedro

2024-03-15 18:27 UTC, frmadem requested changes

2024-03-15 18:27 UTC, frmadem commented on data/componentes/衣,ropa.yml
> +componentes: ['<span style="color: rgb(170, 0, 0);">Como componente: capa (usando forma alt.); bufanda (usando mitad inferior).</span>']
Sobran estilos.

2024-03-15 18:27 UTC, frmadem commented on data/懐,bolsillo.yml
> +componentes: ['Corazón', 'Clavo', 'Ojo tumbado', 'Ropa']
Las claves TIENEN que coincidir con las existentes para los componentes.

2024-03-15 18:27 UTC, frmadem commented on data/敢,osadía.yml
> +    Marineros poniéndose un clavo (エ) en el oído (耳) para demostrar su osadía al capataz (攵).
Cuando cruzan el cabo de Hornos

2024-03-15 18:27 UTC, frmadem commented on data/曼,mandala.yml
> +componentes: ['Día', 'Ojo tumbado', 'Entrepierna']
Los componentes TIENEN que coincidir con las claves.

2024-03-18 14:03 UTC, frmadem requested changes

2024-03-18 14:03 UTC, frmadem commented on data/職,puesto_de_trabajo.yml
> +    El buen trabajador es el que se mantiene en su puesto de trabajo aún con barullo (耳, 音, 戈) .
Separa los tres kanjis en tres componentes please

2024-05-12 10:51 UTC, frmadem requested changes

2024-05-12 10:51 UTC, frmadem commented on data/敢,osadía.yml
> +    Marineros poniéndose un clavo (エ) en el oído (耳) para demostrar su osadía cuando cruzan el cabo de Hornos al capataz (攵).
no es oído es oreja.

2024-05-12 10:51 UTC, frmadem commented on data/敢,osadía.yml
> +    Marineros poniéndose un clavo (エ) en el oído (耳) para demostrar su osadía cuando cruzan el cabo de Hornos al capataz (攵).
al capataz del barco

2024-05-12 16:03 UTC, DjHexaedro commented on data/componentes/衣,ropa.yml
> +historia: >
Non teño a historia orixinal apuntada, así que inventei unha aínda que sexa temporal. Se non é válida necesitaría que alguén me proporcionase a correcta ou unha alternativa

2024-05-13 15:09 UTC, frmadem approved these changes
LGTM!

2024-05-13 15:48 UTC, merged