Update 阻,estorbo.yml
eoi-japones/kanji-data pull request #277
Opened 2024-12-09 20:05 UTC by Kikumei

Historia reajustada

2024-12-09 21:44 UTC, frmadem approved these changes
LGTM!

2024-12-09 21:46 UTC, frmadem requested changes
```sin que nos moleste apilar sus cueros cabelludos en una estantería```

2024-12-13 12:01 UTC, Kikumei commented
Hecho!

2025-02-11 10:01 UTC, frmadem approved these changes
LGTM!

2025-02-11 10:23 UTC, merged