Kanjis de avanzado 13/12/2024
eoi-japones/kanji-data pull request #300
Opened 2024-12-15 22:40 UTC by davconde

2024-12-16 08:21 UTC, frmadem requested changes

2024-12-16 08:21 UTC, frmadem commented on data/濃,concentrado.yml
> +  hay que echarles agua (氵) antes de poder usarlos.
rebajarlos con agua

2024-12-16 08:21 UTC, frmadem commented on data/辰,dragón_signo.yml
> +  jóvenes llevan la horquilla (衣) de un dragón.
No es el componente de horquilla

2024-12-16 08:21 UTC, frmadem commented on data/寅,tigre_signo.yml
> +  brote (一),(由) del que destacaban las piernas (ハ) agitándose con espasmos.
los miembros que colgaban como patas () agitándose con espamos.

2024-12-16 08:21 UTC, frmadem commented on data/典,código.yml
> +  Un código es un conjunto de normas, que son una gran herramienta (一),(ハ)
banco de herramientas tiene un componente no sé si chuta ya bien la referencia a componentes custom. Le doy un vistazo

2024-12-18 22:59 UTC, davconde commented on data/辰,dragón_signo.yml
> +  jóvenes llevan la horquilla (衣) de un dragón.
Actualizado a `镸`. Es el que kanji que tiene registrado `horquilla` como componente, la parte correspondiente que interesa no tiene caracter.

2024-12-18 23:00 UTC, davconde commented on data/典,código.yml
> +  Un código es un conjunto de normas, que son una gran herramienta (一),(ハ)
Cambiado, supongo que si se accede por id es la sintaxis correcta. Si no, avisa y cambio

2024-12-25 17:41 UTC, frmadem approved these changes
LGTM!

2024-12-25 19:22 UTC, merged