Kanjis de avanzado 05/04/2024
eoi-japones/kanji-data pull request #62
Opened 2024-04-06 01:56 UTC by davconde

2024-04-07 15:33 UTC, frmadem commented on data/仁,humanitario.yml
> +  Pare ser humanitario en la vida, no hace falta nada más que al menos dos (二)
Pare - Para

No hace falta nada más que dos personas.

2024-04-07 15:34 UTC, frmadem commented on data/倒,derrocamiento.yml
> +  - llegar
Es llegada no llegar

2024-04-07 15:34 UTC, frmadem commented on data/到,llegar.yml
> +clave: llegar
Es llegada la clave, no llegar.

2024-04-07 15:34 UTC, frmadem commented on data/到,llegar.yml
> +  El clímax (至) de cualquier buena historia de aventuras llega cuando el héroe
Resaltar llegada con negrita.

2024-04-07 15:36 UTC, frmadem requested changes

2024-04-07 15:36 UTC, frmadem commented on data/室,sala.yml
> +  el clímax (至) de tu hogar para causar una buena impresión.
de tu hogar, decoración, belleza, artículos de lujo... para causar una buena impresión.

2024-04-07 15:36 UTC, frmadem commented on data/至,clímax.yml
> +  acorralado contra una pared(一, 厶).
Separar (一, 厶) en dos partes (一), (厶) para que se puedan generar los hiperlinks.

2024-04-07 20:47 UTC, davconde commented on data/到,llegar.yml
> +  El clímax (至) de cualquier buena historia de aventuras llega cuando el héroe
Con formato markdown estándar rodeando de doble asterisco lo entiende la app?

2024-04-09 14:54 UTC, frmadem approved these changes
LGTM!

2024-04-09 15:06 UTC, merged