Kanjis de avanzado 12/04/2024
eoi-japones/kanji-data pull request #66
Opened 2024-04-13 01:03 UTC by davconde

2024-04-13 01:07 UTC, davconde commented on data/久,duradero.yml
> +  La punta de una flecha en contacto con la cuerda de un arco, apuntándote con
No tenía la historia de clase, si había. Puse esta basada en el origen según el diccionario Outlier:
> Form explanation
> 久 【キュウ、ク】 depicts the end of an arrow that makes contact with the bowstring, which is also its original meaning. Its modern meaning “long time” is via sound loan.

2024-04-15 08:29 UTC, frmadem requested changes

2024-04-15 08:29 UTC, frmadem commented on data/久,duradero.yml
> +  La punta de una flecha en contacto con la cuerda de un arco, apuntándote con
La historia de clase es una persona (人) empaquetada (勹) como una "momia", es decir algo muy MUY *duradero*.

2024-04-15 08:29 UTC, frmadem commented on data/匹,igual.yml
> +  Si encuentras una caja llena de cadáveres con varias piernas asomando, no
Faltan (匚) y piernas (儿) en las referencias de la historia.

2024-04-15 08:29 UTC, frmadem commented on data/区,distrito.yml
> +  Cada distrito es como un haz (丶),(ノ) de edificios dentro de una caja (匚) de
el componente correcto sería haz (乂)

2024-04-15 08:29 UTC, frmadem commented on data/史,historia.yml
> +  quienes están bajo el brazo del poder (丶),(ノ).
Componente de haz (乂)

2024-04-16 23:59 UTC, merged