Kanjis de básico 19/04/2024
eoi-japones/kanji-data pull request #69
Opened 2024-04-21 13:26 UTC by davconde

2024-04-22 07:32 UTC, frmadem requested changes

2024-04-22 07:32 UTC, frmadem commented on data/号,apodo.yml
> +  llevado atados como un lazo (一), (勹) toda su vida, estando siempre en boca de
@davconde existe el componente 丂, empléalo porfa.

2024-04-22 07:32 UTC, frmadem commented on data/巧,habilidad.yml
> +  La técnica (工) de la caza con lazo (一), (勹) no require de ninguna habilidad.
Existe el componente 丂

2024-04-22 07:32 UTC, frmadem commented on data/汚,sucio.yml
> +  La caza con lazo (一), (勹) es tan sucia que más de uno la ha abandonado entre
Existe el component 丂

2024-04-22 09:15 UTC, davconde commented on data/号,apodo.yml
> +  llevado atados como un lazo (一), (勹) toda su vida, estando siempre en boca de
Ok, esa entrada está rota en [Jisho](https://jisho.org/search/%E4%B8%82%20%23kanji#radical), non pon que teña partes nin o lista como un radical. Se sabes dalgún recurso mellor de cara a futuro, agradécese.

2024-04-23 07:51 UTC, frmadem approved these changes
LGTM!

2024-04-23 08:50 UTC, merged