Kanjis de avanzado 26/04/2024
eoi-japones/kanji-data pull request #78
Opened 2024-04-29 22:21 UTC by davconde

2024-05-01 22:36 UTC, frmadem requested changes

2024-05-01 22:36 UTC, frmadem commented on data/遊,jugar.yml
> +historia: "El estandarte (方),(𠂉) de cualquier sociedad debería ser tener sus caminos (辶) llenos de niños (子) jugando."
El componente estandarte (𭤨) existe.

2024-05-01 22:36 UTC, frmadem commented on data/旅,viaje.yml
> +historia: "Un auténtico viajero lleva andrajos (衣) como su estandarte (方),(𠂉)."
El componente estandarte existe (𭤨).

2024-05-01 22:36 UTC, frmadem commented on data/施,limosna.yml
> +historia: "No le des un pescado. Enséñale a pescar. Dar limosna puede parecer el estandarte (方),(𠂉) de la compasión, pero realmente es un escorpión (也) que muerde a la gente haciéndola dependiente y
El componente de estandarte existe (𭤨).

2024-05-01 22:36 UTC, frmadem commented on data/敝,triturar.yml
> +﻿id: 敝
Mover el solo componente a la carpeta data/componentes.

2024-05-01 22:37 UTC, frmadem commented on data/遊,jugar.yml
> +historia: "El estandarte (方),(𠂉) de cualquier sociedad debería ser tener sus caminos (辶) llenos de niños (子) jugando."
Falta también el componente de estandarte (solo componente)

2024-05-03 09:43 UTC, davconde commented on data/遊,jugar.yml
> +historia: "El estandarte (方),(𠂉) de cualquier sociedad debería ser tener sus caminos (辶) llenos de niños (子) jugando."
No se permite en el formulario: 
![image](https://github.com/eoi-japones/kanji-data/assets/25469848/797b8edf-3315-48cf-b2f6-d7c0a40f6739)

2024-05-03 17:23 UTC, frmadem approved these changes
LGTM!

2024-05-03 20:07 UTC, merged