Kanjis de avanzado 24/05/2024
eoi-japones/kanji-data pull request #89
Opened 2024-05-24 23:39 UTC by davconde

2024-05-26 11:35 UTC, frmadem requested changes

2024-05-26 11:35 UTC, frmadem commented on data/componentes/𠂢,porquería.yml
> +﻿id: "\uD840\uDCA2"
no se ve el kanji

2024-05-26 11:35 UTC, frmadem commented on data/司,director.yml
> +historia: "Un director muy estricto al que si alguien le lleva la contraria, acabará colgado del techo (一) con una percha (\uD840\uDCCC) por la boca (口)."
El caracter está mal

2024-05-26 11:35 UTC, frmadem commented on data/嗣,sucesor.yml
> +  El sucesor de un antiguo empleado que apunta en su bloc de notas (冊) todo lo
No, es mejor la historia de un empleado que apunta en el bloc de notas toods los consejos que salen por la boca () de su director () al que va a suceder prnto.

2024-05-26 11:35 UTC, frmadem commented on data/幻,fantasma.yml
> +historia: "Un fantasma muy joven en aún en su etapa de capullo (幺) en la vida, que todavía asustado por tener que asustar a otros, prefiere quedarse con su manta colgado en una percha (\uD840\uDCCC).
Percha no se ve.

2024-05-26 11:35 UTC, frmadem commented on data/派,facción.yml
> +historia: "Cuando un todo se divide en facciones, tras el conflicto será el agua (氵) quien arrastre (𠂆) los andrajos (衣) de los antiguos miembros."
los andrajos de una de las dos partes.

2024-05-26 11:35 UTC, frmadem commented on data/脈,vena.yml
> +historia: "Los conductos que tenemos por todas nuestras partes del cuerpo (月), transportando la porquería (\uD840\uDCA2) que ya no necesitamos."
kanji mal

2024-05-26 11:35 UTC, frmadem commented on data/衆,muchedumbre.yml
> +historia: "Las muchedumbres son algo que siempre demandan sangre (血), siendo capaces de cometer actos atroces y cualquier otro tipo de porquería (\uD840\uDCA2)."
mal el componente

2024-05-26 22:08 UTC, davconde commented on data/司,director.yml
> +historia: "Un director muy estricto al que si alguien le lleva la contraria, acabará colgado del techo (一) con una percha (\uD840\uDCCC) por la boca (口)."
Y cuál sería? Con este mismo caracter me sale la misma definición en [Jisho](https://jisho.org/search/%E5%8F%B8%20%23kanji) y [Wiktionary](https://en.wiktionary.org/wiki/%E5%8F%B8#Japanese).

2024-05-26 22:09 UTC, davconde commented on data/脈,vena.yml
> +historia: "Los conductos que tenemos por todas nuestras partes del cuerpo (月), transportando la porquería (\uD840\uDCA2) que ya no necesitamos."
Me sale igual en [Jisho](https://jisho.org/search/%E8%84%88%20%23kanji) y [Wiktionary](https://en.wiktionary.org/wiki/%E8%84%88#Japanese).

2024-05-27 11:10 UTC, frmadem approved these changes
LGTM!

2024-05-27 11:50 UTC, merged