Kanjis del 31/05/2024
eoi-japones/kanji-data pull request #91
Opened 2024-06-01 03:11 UTC by davconde

2024-06-01 03:17 UTC, davconde commented on data/晩,anochecer.yml
Esta clave está repetida ([宵](https://github.com/eoi-japones/kanji-data/blob/main/data/%E5%AE%B5%2Canochecer.yml))

2024-06-01 03:19 UTC, davconde commented on data/鹿,ciervo.yml
No veo que exista el caracter para llave.
https://en.wiktionary.org/wiki/%E9%B9%BF

2024-06-02 15:47 UTC, frmadem requested changes

2024-06-02 20:04 UTC, davconde commented on data/晩,crepúsculo_vespertino.yml
> +clave: crepúsculo_vespertino
Lo cambié de anochecer (la acepción que sale en [Jisho](https://jisho.org/search/%E6%99%A9%20%23kanji)/[Wiktionary](https://en.wiktionary.org/wiki/%E6%99%A9) junto a noche) por crepúsculo vespertino para indicar que nunca hace referencia al matutino. Así o lo simplifico a "crepúsculo" aunque pueda dar lugar a confusión?

![image](https://github.com/eoi-japones/kanji-data/assets/25469848/aa0b95bb-a476-4ba4-9172-34009c5f4a53)

2024-06-06 07:10 UTC, frmadem commented on data/晩,crepúsculo_vespertino.yml
> +clave: crepúsculo_vespertino
me parece bien.

2024-06-06 07:16 UTC, frmadem requested changes

2024-06-06 07:16 UTC, frmadem commented on data/鹿,ciervo.yml
> +  sus cualidades.
En este punto necesito que pongas que es **doble llave** si te fijas son 2 llaves. 

Por eso quizá sería mejor aquí: 


En las cuevas (广) se pintaban a personas con máscaras de ciervos. ¿Por qué lo hacían? la hipótesis es que querían adquririr los poderes y cualidades de los ciervos con los que se comparaban. (比). ¿Es esto cierto? Es sólo una teoría, evidentemente la Historia ha guardado la verdad bajo doble  llave (㐄) ... probablemente para siempre...

2024-06-06 22:26 UTC, frmadem approved these changes
LGTM!

2024-06-06 22:43 UTC, merged